version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: opssentinel-api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    networks:
      - opssentinel-net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: opssentinel-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api
    networks:
      - opssentinel-net

networks:
  opssentinel-net:
    driver: bridge